### ISSUE TITLE
Tests can't pass in GPU mode

### ISSUE THREAD

**Issue by gcp** [leela-zero/leela-zero#2214]
Was broken by #2188.

Some of the internal variables are no longer set up correctly and the tests end up bypassing the expected initialization.

```
Tensor Core support: No.

Thread 1 "tests" received signal SIGFPE, Arithmetic exception.
0x0000555555610bf3 in OpenCLScheduler<float>::initialize(int) (this=0x5555569d72b0, channels=8)
    at ../src/OpenCLScheduler.cpp:116
116         auto num_worker_threads = cfg_num_threads / cfg_batch_size / (m_opencl.size() + 1) + 1;
(gdb) bt
#0  0x0000555555610bf3 in OpenCLScheduler<float>::initialize(int) (this=0x5555569d72b0, channels=8)
    at ../src/OpenCLScheduler.cpp:116
#1  0x00005555555dc519 in Network::init_net (this=this@entry=0x7ffff7e4f010, 
    channels=channels@entry=8, pipe=...) at ../src/Network.cpp:385
#2  0x00005555555e782c in Network::select_precision (this=this@entry=0x7ffff7e4f010, 
    channels=channels@entry=8) at ../src/Network.cpp:421
#3  0x00005555555e9cbc in Network::initialize (this=this@entry=0x7ffff7e4f010, 
    playouts=playouts@entry=1073741823, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
weightsfile=) at ../src/Network.cpp:566
#4  0x0000555555619c3b in LeelaEnv::SetUp() (this=<optimized out>) at ../src/tests/gtests.cpp:87
#5  0x000055555566aaae in testing::internal::SetUpEnvironment(testing::Environment*) ()
#6  0x0000555555686f47 in void (*std::for_each<__gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*, std::allocator<testing::Environment*> > >, void (*)(testing::Environment*)>(__gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*, std::allocator<testing::Environment*> > >, __gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*, std::allocator<testing::Environment*> > >, void (*)(testing::Environment*)))(testing::Environment*) ()
#7  0x0000555555680c65 in void testing::internal::ForEach<std::vector<testing::Environment*, std::allocator<testing::Environment*> >, void (*)(testing::Environment*)>(std::vector<testing::Environment*, std::allocator<testing::Environment*> > const&, void (*)(testing::Environment*)) ()
#8  0x000055555566ad1a in testing::internal::UnitTestImpl::RunAllTests() ()
#9  0x000055555568669d in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#10 0x000055555568060d in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#11 0x0000555555669816 in testing::UnitTest::Run() ()
#12 0x0000555555657c64 in RUN_ALL_TESTS() ()
#13 0x0000555555657bf3 in main ()
```

**Comment by wonderingabout** [comment]
correct me if mistaken, but is it worth fixing this considering long term plan to support CUDA and cuDNN (and tensorRT maybe) ?

**Comment by gcp** [comment]
I have no idea why you think that's in any way relevant.

**Comment by wonderingabout** [comment]
this was a question

i dont know if leela zero CUDA cuDNN (and maybe tensorRT too) implementation has a different code and its own batching support

(like in phoenixgo for example)

**Comment by gcp** [comment]
Who knows? It just has nothing whatsoever to do with this problem.

**Comment by wonderingabout** [comment]
but regardless of the answer, i just realized i overlooked the case of amd users who will benefit of the current batching with opencl

**Comment by wonderingabout** [comment]
indeed this is 2 different problems, my bad

but they are both related to the batching issue, but then i guess we'll see how the CUDA and cuDNN will go in the first place :+1:

**Comment by ihavnoid** [comment]
Argh.  How do I run the tests in GPU mode?

**Comment by ihavnoid** [comment]
Well, the simple fix is to put a more 'sane' default value which isn't zero (perhaps 1 thread with batch size of 1?).  What do you think?

**Comment by gcp** [comment]
>What do you think?

I'd like a fix so that if you just run ```./leelaz -h```, the default values for threads and batchsize are shown. It feels a little bit strange right now that you have no idea what it is actually picking.

**Comment by gcp** [comment]
>Argh. How do I run the tests in GPU mode?

Just compile it with GPU support and run the ```./tests``` exe.

**Comment by ihavnoid** [comment]
> 
> I'd like a fix so that if you just run `./leelaz -h`, the default values for threads and batchsize are shown (as it was before for threads). It feels a little bit strange right now that you have no idea what it is actually picking.

I am not sure what to do though.  One good thing to do is to pick a reasonable default regardless of what is running.  The reasonable default will be quite different depending on other parameters (e.g., number of GPUs, CPU mode vs. GPU mode, etc.) and -h reporting different default values depending on the situation is wierd, too.
What if I just print out the number of threads / batch sizes large and clearly, create an 'auto' option, and use 'auto' as default?

**Comment by gcp** [comment]
>-h reporting different default values depending on the situation is wierd, too.

I don't see the problem with this. Different hardware, different defaults. For threads this is very logical.

**Comment by gcp** [comment]
>e.g., number of GPUs, CPU mode vs. GPU mode, etc

We know what the default picks for all of those would be.

I guess the issue is things like it printing that, say, 16 threads would be the default, but if you also specify CPU-mode and not the amount of threads, it won't actually use 16?

In that case you're right.
